name = "fitness-webapp"
compatibility_date = "2024-12-18"
main = "workers/api/index.ts"

[env.development]
name = "fitness-webapp-dev"

[env.production]  
name = "fitness-webapp-prod"

[[d1_databases]]
binding = "DB"
database_name = "fitness-app-db"
database_id = "your-database-id-here"

[build]
command = "npm run build"

[vars]
ENVIRONMENT = "development"

# Example migration command:
# npx wrangler d1 execute fitness-app-db --file=./database/migrations/001_initial.sql